### ISSUE TITLE
grep results are not precise use -w switch to be more concrete (Debian 9)

### ISSUE THREAD

**Issue by Daigtas** [gameap/auto-install-scripts#1]
https://github.com/gameap/auto-install-scripts/blob/e1f7483858184a55f755e575e961bea9aecde773/install.sh#L4
At that point i've changed he command to 
`os=$(cat /etc/os-release | grep -w "ID" | cut -d= -f2 | head -1)`
made grep more precise with -w switch becouse the results where VERSION_ID=9 and ID=debian, both has an ID in it.

**Comment by et-nik** [comment]
Thanks. Fixed.
